// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    category_code, name, parent_category_id, description
) VALUES (
    $1, $2, $3, $4
) RETURNING category_id, category_code, name, parent_category_id, description, created_at
`

type CreateCategoryParams struct {
	CategoryCode     string         `json:"category_code"`
	Name             string         `json:"name"`
	ParentCategoryID sql.NullInt32  `json:"parent_category_id"`
	Description      sql.NullString `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.CategoryCode,
		arg.Name,
		arg.ParentCategoryID,
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryCode,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories 
WHERE category_id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, categoryID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT category_id, category_code, name, parent_category_id, description, created_at FROM categories 
WHERE category_id = $1
`

func (q *Queries) GetCategory(ctx context.Context, categoryID int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, categoryID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryCode,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByCode = `-- name: GetCategoryByCode :one
SELECT category_id, category_code, name, parent_category_id, description, created_at FROM categories 
WHERE category_code = $1
`

func (q *Queries) GetCategoryByCode(ctx context.Context, categoryCode string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByCode, categoryCode)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryCode,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, category_code, name, parent_category_id, description, created_at FROM categories 
ORDER BY category_id
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryCode,
			&i.Name,
			&i.ParentCategoryID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCategories = `-- name: ListRootCategories :many
SELECT category_id, category_code, name, parent_category_id, description, created_at FROM categories 
WHERE parent_category_id IS NULL
ORDER BY category_id
`

func (q *Queries) ListRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryCode,
			&i.Name,
			&i.ParentCategoryID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubCategories = `-- name: ListSubCategories :many
SELECT category_id, category_code, name, parent_category_id, description, created_at FROM categories 
WHERE parent_category_id = $1
ORDER BY category_id
`

func (q *Queries) ListSubCategories(ctx context.Context, parentCategoryID sql.NullInt32) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listSubCategories, parentCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryCode,
			&i.Name,
			&i.ParentCategoryID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories 
SET 
    name = $2,
    parent_category_id = $3,
    description = $4
WHERE category_id = $1
RETURNING category_id, category_code, name, parent_category_id, description, created_at
`

type UpdateCategoryParams struct {
	CategoryID       int32          `json:"category_id"`
	Name             string         `json:"name"`
	ParentCategoryID sql.NullInt32  `json:"parent_category_id"`
	Description      sql.NullString `json:"description"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.CategoryID,
		arg.Name,
		arg.ParentCategoryID,
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryCode,
		&i.Name,
		&i.ParentCategoryID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
