// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	ActivateSupplier(ctx context.Context, supplierID int32) error
	ApproveStockAdjustment(ctx context.Context, arg ApproveStockAdjustmentParams) (StockAdjustment, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (PurchaseOrderItem, error)
	CreateStockAdjustment(ctx context.Context, arg CreateStockAdjustmentParams) (StockAdjustment, error)
	CreateStockAdjustmentItem(ctx context.Context, arg CreateStockAdjustmentItemParams) (CreateStockAdjustmentItemRow, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error)
	CreateStockTransfer(ctx context.Context, arg CreateStockTransferParams) (StockTransfer, error)
	CreateStockTransferItem(ctx context.Context, arg CreateStockTransferItemParams) (StockTransferItem, error)
	CreateStocktake(ctx context.Context, arg CreateStocktakeParams) (StockTake, error)
	CreateStocktakeItem(ctx context.Context, arg CreateStocktakeItemParams) (StocktakeItem, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error)
	DeactivateLocation(ctx context.Context, locationID int32) error
	DeactivateSupplier(ctx context.Context, supplierID int32) error
	DeactivateWarehouse(ctx context.Context, warehouseID int32) error
	GetActiveStocktakes(ctx context.Context) ([]GetActiveStocktakesRow, error)
	GetInventory(ctx context.Context, inventoryID int32) (Inventory, error)
	GetInventoryByLocation(ctx context.Context, arg GetInventoryByLocationParams) (Inventory, error)
	GetInventoryByProductWarehouse(ctx context.Context, arg GetInventoryByProductWarehouseParams) (Inventory, error)
	GetLocation(ctx context.Context, locationID int32) (Location, error)
	GetLocationByCode(ctx context.Context, arg GetLocationByCodeParams) (Location, error)
	GetProduct(ctx context.Context, productID int32) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetProductMovementHistory(ctx context.Context, arg GetProductMovementHistoryParams) ([]GetProductMovementHistoryRow, error)
	GetPurchaseOrder(ctx context.Context, poID int32) (GetPurchaseOrderRow, error)
	GetPurchaseOrderItems(ctx context.Context, poID int32) ([]GetPurchaseOrderItemsRow, error)
	GetStockMovement(ctx context.Context, movementID int32) (StockMovement, error)
	GetStocktake(ctx context.Context, stocktakeID int32) (GetStocktakeRow, error)
	GetStocktakeItems(ctx context.Context, stocktakeID int32) ([]GetStocktakeItemsRow, error)
	GetStocktakeVariances(ctx context.Context, stocktakeID int32) ([]GetStocktakeVariancesRow, error)
	GetSupplier(ctx context.Context, supplierID int32) (Supplier, error)
	GetSupplierByCode(ctx context.Context, code string) (Supplier, error)
	GetSupplierPerformance(ctx context.Context, supplierID int32) (GetSupplierPerformanceRow, error)
	GetSupplierProducts(ctx context.Context, arg GetSupplierProductsParams) ([]Product, error)
	GetWarehouse(ctx context.Context, warehouseID int32) (Warehouse, error)
	GetWarehouseByCode(ctx context.Context, code string) (Warehouse, error)
	GetWarehouseInventorySummary(ctx context.Context) ([]GetWarehouseInventorySummaryRow, error)
	ListActiveSuppliers(ctx context.Context) ([]Supplier, error)
	ListAllSuppliers(ctx context.Context, arg ListAllSuppliersParams) ([]Supplier, error)
	ListAllWarehouses(ctx context.Context) ([]Warehouse, error)
	ListExpiringInventory(ctx context.Context) ([]ListExpiringInventoryRow, error)
	ListInventoryByProduct(ctx context.Context, productID int32) ([]ListInventoryByProductRow, error)
	ListInventoryByWarehouse(ctx context.Context, arg ListInventoryByWarehouseParams) ([]ListInventoryByWarehouseRow, error)
	ListLocationsByWarehouse(ctx context.Context, warehouseID int32) ([]Location, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsBelowReorderPoint(ctx context.Context) ([]ListProductsBelowReorderPointRow, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error)
	ListPurchaseOrdersByStatus(ctx context.Context, arg ListPurchaseOrdersByStatusParams) ([]ListPurchaseOrdersByStatusRow, error)
	ListStockMovementsByProduct(ctx context.Context, arg ListStockMovementsByProductParams) ([]ListStockMovementsByProductRow, error)
	ListStockMovementsByType(ctx context.Context, arg ListStockMovementsByTypeParams) ([]ListStockMovementsByTypeRow, error)
	ListStockMovementsByWarehouse(ctx context.Context, arg ListStockMovementsByWarehouseParams) ([]ListStockMovementsByWarehouseRow, error)
	ListStocktakes(ctx context.Context, arg ListStocktakesParams) ([]ListStocktakesRow, error)
	ListStocktakesByWarehouse(ctx context.Context, warehouseID int32) ([]StockTake, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListWarehouses(ctx context.Context) ([]Warehouse, error)
	ReleaseInventoryReservation(ctx context.Context, arg ReleaseInventoryReservationParams) (Inventory, error)
	ReserveInventory(ctx context.Context, arg ReserveInventoryParams) (Inventory, error)
	SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]Supplier, error)
	SoftDeleteProduct(ctx context.Context, productID int32) error
	UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) (Inventory, error)
	UpdateInventoryStatus(ctx context.Context, arg UpdateInventoryStatusParams) (Inventory, error)
	UpdateLastReorderDate(ctx context.Context, productID int32) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdatePurchaseOrderItemReceivedQty(ctx context.Context, arg UpdatePurchaseOrderItemReceivedQtyParams) (PurchaseOrderItem, error)
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) (PurchaseOrder, error)
	UpdateStockTransferItemQuantities(ctx context.Context, arg UpdateStockTransferItemQuantitiesParams) (StockTransferItem, error)
	UpdateStockTransferStatus(ctx context.Context, arg UpdateStockTransferStatusParams) (StockTransfer, error)
	UpdateStocktakeItemCount(ctx context.Context, arg UpdateStocktakeItemCountParams) (StocktakeItem, error)
	UpdateStocktakeStatus(ctx context.Context, arg UpdateStocktakeStatusParams) (StockTake, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error)
}

var _ Querier = (*Queries)(nil)
