// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stock_adjustments.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const approveStockAdjustment = `-- name: ApproveStockAdjustment :one
UPDATE stock_adjustments 
SET 
    status = 'approved',
    approved_by = $2,
    approved_at = CURRENT_TIMESTAMP
WHERE adjustment_id = $1 AND status = 'pending'
RETURNING adjustment_id, adjustment_number, warehouse_id, adjustment_date, reason, status, total_value, notes, approved_by, approved_at, created_by, created_at
`

type ApproveStockAdjustmentParams struct {
	AdjustmentID int32       `json:"adjustment_id"`
	ApprovedBy   pgtype.Int4 `json:"approved_by"`
}

func (q *Queries) ApproveStockAdjustment(ctx context.Context, arg *ApproveStockAdjustmentParams) (*StockAdjustment, error) {
	row := q.db.QueryRow(ctx, approveStockAdjustment, arg.AdjustmentID, arg.ApprovedBy)
	var i StockAdjustment
	err := row.Scan(
		&i.AdjustmentID,
		&i.AdjustmentNumber,
		&i.WarehouseID,
		&i.AdjustmentDate,
		&i.Reason,
		&i.Status,
		&i.TotalValue,
		&i.Notes,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createStockAdjustment = `-- name: CreateStockAdjustment :one
INSERT INTO stock_adjustments (
    adjustment_number, warehouse_id, adjustment_date,
    reason, status, total_value, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING adjustment_id, adjustment_number, warehouse_id, adjustment_date, reason, status, total_value, notes, approved_by, approved_at, created_by, created_at
`

type CreateStockAdjustmentParams struct {
	AdjustmentNumber string               `json:"adjustment_number"`
	WarehouseID      int32                `json:"warehouse_id"`
	AdjustmentDate   time.Time            `json:"adjustment_date"`
	Reason           AdjustmentReason     `json:"reason"`
	Status           NullAdjustmentStatus `json:"status"`
	TotalValue       decimal.Decimal      `json:"total_value"`
	Notes            pgtype.Text          `json:"notes"`
	CreatedBy        pgtype.Int4          `json:"created_by"`
}

func (q *Queries) CreateStockAdjustment(ctx context.Context, arg *CreateStockAdjustmentParams) (*StockAdjustment, error) {
	row := q.db.QueryRow(ctx, createStockAdjustment,
		arg.AdjustmentNumber,
		arg.WarehouseID,
		arg.AdjustmentDate,
		arg.Reason,
		arg.Status,
		arg.TotalValue,
		arg.Notes,
		arg.CreatedBy,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.AdjustmentID,
		&i.AdjustmentNumber,
		&i.WarehouseID,
		&i.AdjustmentDate,
		&i.Reason,
		&i.Status,
		&i.TotalValue,
		&i.Notes,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return &i, err
}

const createStockAdjustmentItem = `-- name: CreateStockAdjustmentItem :one
INSERT INTO stock_adjustment_items (
    adjustment_id, product_id, quantity_before,
    quantity_adjusted, cost_price, reason
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING adjustment_item_id,
    quantity_before + quantity_adjusted as quantity_after,
    quantity_adjusted * cost_price as adjustment_value
`

type CreateStockAdjustmentItemParams struct {
	AdjustmentID     int32           `json:"adjustment_id"`
	ProductID        int32           `json:"product_id"`
	QuantityBefore   int32           `json:"quantity_before"`
	QuantityAdjusted int32           `json:"quantity_adjusted"`
	CostPrice        decimal.Decimal `json:"cost_price"`
	Reason           pgtype.Text     `json:"reason"`
}

type CreateStockAdjustmentItemRow struct {
	AdjustmentItemID int32 `json:"adjustment_item_id"`
	QuantityAfter    int32 `json:"quantity_after"`
	AdjustmentValue  int32 `json:"adjustment_value"`
}

func (q *Queries) CreateStockAdjustmentItem(ctx context.Context, arg *CreateStockAdjustmentItemParams) (*CreateStockAdjustmentItemRow, error) {
	row := q.db.QueryRow(ctx, createStockAdjustmentItem,
		arg.AdjustmentID,
		arg.ProductID,
		arg.QuantityBefore,
		arg.QuantityAdjusted,
		arg.CostPrice,
		arg.Reason,
	)
	var i CreateStockAdjustmentItemRow
	err := row.Scan(&i.AdjustmentItemID, &i.QuantityAfter, &i.AdjustmentValue)
	return &i, err
}
