// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transfers.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createStockTransfer = `-- name: CreateStockTransfer :one
INSERT INTO stock_transfers (
    transfer_number, from_warehouse_id, to_warehouse_id,
    status, transfer_date, expected_completion_date,
    notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING transfer_id, transfer_number, from_warehouse_id, to_warehouse_id, status, transfer_date, expected_completion_date, notes, created_by, created_at
`

type CreateStockTransferParams struct {
	TransferNumber         string         `json:"transfer_number"`
	FromWarehouseID        int32          `json:"from_warehouse_id"`
	ToWarehouseID          int32          `json:"to_warehouse_id"`
	Status                 TransferStatus `json:"status"`
	TransferDate           time.Time      `json:"transfer_date"`
	ExpectedCompletionDate time.Time      `json:"expected_completion_date"`
	Notes                  sql.NullString `json:"notes"`
	CreatedBy              sql.NullInt32  `json:"created_by"`
}

func (q *Queries) CreateStockTransfer(ctx context.Context, arg CreateStockTransferParams) (StockTransfer, error) {
	row := q.db.QueryRowContext(ctx, createStockTransfer,
		arg.TransferNumber,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.Status,
		arg.TransferDate,
		arg.ExpectedCompletionDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i StockTransfer
	err := row.Scan(
		&i.TransferID,
		&i.TransferNumber,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.Status,
		&i.TransferDate,
		&i.ExpectedCompletionDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createStockTransferItem = `-- name: CreateStockTransferItem :one
INSERT INTO stock_transfer_items (
    transfer_id, product_id, quantity,
    from_location_id, to_location_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING transfer_item_id, transfer_id, product_id, quantity, quantity_sent, quantity_received, from_location_id, to_location_id
`

type CreateStockTransferItemParams struct {
	TransferID     int32         `json:"transfer_id"`
	ProductID      int32         `json:"product_id"`
	Quantity       int32         `json:"quantity"`
	FromLocationID sql.NullInt32 `json:"from_location_id"`
	ToLocationID   sql.NullInt32 `json:"to_location_id"`
}

func (q *Queries) CreateStockTransferItem(ctx context.Context, arg CreateStockTransferItemParams) (StockTransferItem, error) {
	row := q.db.QueryRowContext(ctx, createStockTransferItem,
		arg.TransferID,
		arg.ProductID,
		arg.Quantity,
		arg.FromLocationID,
		arg.ToLocationID,
	)
	var i StockTransferItem
	err := row.Scan(
		&i.TransferItemID,
		&i.TransferID,
		&i.ProductID,
		&i.Quantity,
		&i.QuantitySent,
		&i.QuantityReceived,
		&i.FromLocationID,
		&i.ToLocationID,
	)
	return i, err
}

const updateStockTransferItemQuantities = `-- name: UpdateStockTransferItemQuantities :one
UPDATE stock_transfer_items 
SET 
    quantity_sent = $2,
    quantity_received = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE transfer_item_id = $1
RETURNING transfer_item_id, transfer_id, product_id, quantity, quantity_sent, quantity_received, from_location_id, to_location_id
`

type UpdateStockTransferItemQuantitiesParams struct {
	TransferItemID   int32 `json:"transfer_item_id"`
	QuantitySent     int32 `json:"quantity_sent"`
	QuantityReceived int32 `json:"quantity_received"`
}

func (q *Queries) UpdateStockTransferItemQuantities(ctx context.Context, arg UpdateStockTransferItemQuantitiesParams) (StockTransferItem, error) {
	row := q.db.QueryRowContext(ctx, updateStockTransferItemQuantities, arg.TransferItemID, arg.QuantitySent, arg.QuantityReceived)
	var i StockTransferItem
	err := row.Scan(
		&i.TransferItemID,
		&i.TransferID,
		&i.ProductID,
		&i.Quantity,
		&i.QuantitySent,
		&i.QuantityReceived,
		&i.FromLocationID,
		&i.ToLocationID,
	)
	return i, err
}

const updateStockTransferStatus = `-- name: UpdateStockTransferStatus :one
UPDATE stock_transfers 
SET 
    status = $2,
    transfer_date = CASE 
        WHEN $2 = 'completed' AND transfer_date IS NULL THEN CURRENT_DATE 
        ELSE transfer_date 
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE transfer_id = $1
RETURNING transfer_id, transfer_number, from_warehouse_id, to_warehouse_id, status, transfer_date, expected_completion_date, notes, created_by, created_at
`

type UpdateStockTransferStatusParams struct {
	TransferID int32          `json:"transfer_id"`
	Status     TransferStatus `json:"status"`
}

func (q *Queries) UpdateStockTransferStatus(ctx context.Context, arg UpdateStockTransferStatusParams) (StockTransfer, error) {
	row := q.db.QueryRowContext(ctx, updateStockTransferStatus, arg.TransferID, arg.Status)
	var i StockTransfer
	err := row.Scan(
		&i.TransferID,
		&i.TransferNumber,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.Status,
		&i.TransferDate,
		&i.ExpectedCompletionDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
