CREATE TYPE "inventory_status" AS ENUM (
  'in_stock',
  'reserved',
  'shipped',
  'returned',
  'damaged'
);

CREATE TYPE "purchase_order_status" AS ENUM (
  'draft',
  'pending',
  'approved',
  'partially_received',
  'completed',
  'cancelled'
);

CREATE TYPE "movement_type" AS ENUM (
  'purchase_receipt',
  'sales_delivery',
  'stock_transfer',
  'stock_adjustment',
  'return',
  'damage',
  'production'
);

CREATE TYPE "transfer_status" AS ENUM (
  'pending',
  'in_transit',
  'completed',
  'cancelled'
);

CREATE TYPE "adjustment_reason" AS ENUM (
  'count_discrepancy',
  'damage',
  'theft',
  'expired',
  'sample',
  'other'
);

CREATE TYPE "adjustment_status" AS ENUM (
  'pending',
  'approved',
  'rejected',
  'completed'
);

CREATE TYPE "stocktake_status" AS ENUM (
  'planned',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TYPE "reconciliation_frequency" AS ENUM (
  'daily',
  'weekly',
  'monthly',
  'quarterly'
);

CREATE TYPE "incident_type" AS ENUM (
  'theft',
  'damage',
  'miscount',
  'expiration',
  'unknown'
);

CREATE TYPE "counting_method" AS ENUM (
  'ABC',
  'random',
  'location_based'
);

CREATE TYPE "identifier_type" AS ENUM (
  'serial',
  'batch',
  'lot',
  'rfid',
  'qr_code'
);

CREATE TYPE "identifier_status" AS ENUM (
  'active',
  'in_transit',
  'sold',
  'returned',
  'damaged'
);

CREATE TYPE "location_movement_type" AS ENUM (
  'pick',
  'putaway',
  'transfer',
  'adjustment'
);

CREATE TYPE "wave_status" AS ENUM (
  'planned',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TYPE "abc_category" AS ENUM (
  'A',
  'B',
  'C'
);

CREATE TYPE "abc_criteria" AS ENUM (
  'value',
  'volume',
  'profit'
);

CREATE TYPE "condition_type" AS ENUM (
  'stock_level',
  'time_based',
  'seasonal',
  'demand_spike'
);

CREATE TYPE "action_type" AS ENUM (
  'create_po',
  'transfer',
  'alert'
);

CREATE TYPE "user_role" AS ENUM (
  'admin',
  'manager',
  'staff',
  'viewer'
);

CREATE TYPE "audit_action" AS ENUM (
  'INSERT',
  'UPDATE',
  'DELETE'
);

CREATE TABLE "products" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "category_id" int,
  "unit_price" decimal(10,2) NOT NULL,
  "cost_price" decimal(10,2),
  "barcode" varchar(100),
  "weight" decimal(10,3),
  "dimensions" varchar(100),
  "supplier_id" int,
  "min_stock_level" int DEFAULT 0,
  "max_stock_level" int,
  "reorder_point" int,
  "safety_stock" int,
  "lead_time_days" int,
  "auto_reorder" boolean DEFAULT false,
  "last_reorder_date" date,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "warehouses" (
  "warehouse_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "address" text,
  "contact_person" varchar(100),
  "contact_phone" varchar(20),
  "contact_email" varchar(100),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "locations" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" int NOT NULL,
  "location_code" varchar(50) NOT NULL,
  "aisle" varchar(20),
  "shelf" varchar(20),
  "bin" varchar(20),
  "max_capacity" int,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "inventory" (
  "inventory_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "warehouse_id" int NOT NULL,
  "location_id" int,
  "quantity" int DEFAULT 0,
  "reserved_quantity" int DEFAULT 0,
  "batch_number" varchar(100),
  "expiry_date" date,
  "manufacturing_date" date,
  "serial_number" varchar(100),
  "status" inventory_status DEFAULT 'in_stock',
  "last_counted_date" date,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "suppliers" (
  "supplier_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "contact_person" varchar(100),
  "email" varchar(100),
  "phone" varchar(20),
  "address" text,
  "tax_id" varchar(50),
  "payment_terms" varchar(100),
  "lead_time_days" int,
  "rating" decimal(3,2),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "parent_category_id" int,
  "description" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "purchase_orders" (
  "po_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "po_number" varchar(50) UNIQUE NOT NULL,
  "supplier_id" int NOT NULL,
  "order_date" date NOT NULL,
  "expected_delivery_date" date,
  "status" purchase_order_status DEFAULT 'draft',
  "total_amount" decimal(10,2),
  "notes" text,
  "created_by" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "purchase_order_items" (
  "po_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "po_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity_ordered" int NOT NULL,
  "quantity_received" int DEFAULT 0,
  "unit_price" decimal(10,2) NOT NULL,
  "total_price" decimal(10,2)
);

CREATE TABLE "stock_movements" (
  "movement_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reference_number" varchar(50) UNIQUE,
  "product_id" int NOT NULL,
  "warehouse_id" int NOT NULL,
  "location_id" int,
  "movement_type" movement_type NOT NULL,
  "quantity_before" int,
  "quantity_change" int NOT NULL,
  "quantity_after" int,
  "reference_id" int,
  "reference_table" varchar(50),
  "notes" text,
  "movement_date" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "created_by" int
);

CREATE TABLE "stock_transfers" (
  "transfer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_number" varchar(50) UNIQUE NOT NULL,
  "from_warehouse_id" int NOT NULL,
  "to_warehouse_id" int NOT NULL,
  "status" transfer_status DEFAULT 'pending',
  "transfer_date" date,
  "expected_completion_date" date,
  "notes" text,
  "created_by" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "stock_transfer_items" (
  "transfer_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transfer_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL,
  "quantity_sent" int DEFAULT 0,
  "quantity_received" int DEFAULT 0,
  "from_location_id" int,
  "to_location_id" int
);

CREATE TABLE "stock_adjustments" (
  "adjustment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adjustment_number" varchar(50) UNIQUE NOT NULL,
  "warehouse_id" int NOT NULL,
  "adjustment_date" date,
  "reason" adjustment_reason NOT NULL,
  "status" adjustment_status DEFAULT 'pending',
  "total_value" decimal(10,2),
  "notes" text,
  "approved_by" int,
  "approved_at" timestamp,
  "created_by" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "stock_adjustment_items" (
  "adjustment_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adjustment_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity_before" int NOT NULL,
  "quantity_adjusted" int NOT NULL,
  "quantity_after" int,
  "cost_price" decimal(10,2),
  "adjustment_value" decimal(10,2),
  "reason" varchar(255)
);

CREATE TABLE "stock_takes" (
  "stocktake_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stocktake_number" varchar(50) UNIQUE NOT NULL,
  "warehouse_id" int NOT NULL,
  "start_date" date,
  "end_date" date,
  "status" stocktake_status DEFAULT 'planned',
  "notes" text,
  "created_by" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "stocktake_items" (
  "stocktake_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stocktake_id" int NOT NULL,
  "product_id" int NOT NULL,
  "location_id" int,
  "system_quantity" int NOT NULL,
  "counted_quantity" int,
  "variance" int,
  "counted_by" int,
  "counted_at" timestamp,
  "notes" varchar(255)
);

CREATE TABLE "reconciliation_rules" (
  "rule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" int,
  "product_category_id" int,
  "reconciliation_frequency" reconciliation_frequency DEFAULT 'weekly',
  "variance_threshold" decimal(5,2) DEFAULT 5,
  "auto_adjust" boolean DEFAULT false,
  "notify_users" json,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "inventory_forecasting" (
  "forecast_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "warehouse_id" int NOT NULL,
  "forecast_date" date NOT NULL,
  "predicted_demand" int,
  "confidence_level" decimal(3,2),
  "calculated_reorder_point" int,
  "calculated_safety_stock" int
);

CREATE TABLE "shrinkage_incidents" (
  "incident_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" int NOT NULL,
  "incident_date" date NOT NULL,
  "incident_type" incident_type NOT NULL,
  "estimated_value" decimal(10,2),
  "detected_by" int,
  "resolved" boolean DEFAULT false,
  "resolution_notes" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "cycle_count_schedule" (
  "schedule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" int,
  "zone_id" int,
  "frequency_days" int DEFAULT 7,
  "counting_method" counting_method DEFAULT 'ABC',
  "last_counted" date,
  "next_scheduled" date,
  "assigned_to" int
);

CREATE TABLE "product_identifiers" (
  "identifier_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "identifier_type" identifier_type NOT NULL,
  "identifier_value" varchar(255) NOT NULL,
  "location_id" int,
  "status" identifier_status,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "location_history" (
  "history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identifier_id" int NOT NULL,
  "from_location_id" int,
  "to_location_id" int,
  "movement_type" location_movement_type,
  "scanned_by" int,
  "scanned_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "device_id" varchar(100)
);

CREATE TABLE "product_suppliers" (
  "product_supplier_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "supplier_id" int NOT NULL,
  "priority" int DEFAULT 1,
  "lead_time_days" int,
  "unit_price" decimal(10,2),
  "min_order_quantity" int,
  "is_active" boolean DEFAULT true,
  "last_order_date" date,
  "performance_rating" decimal(3,2)
);

CREATE TABLE "picking_routes" (
  "route_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" int NOT NULL,
  "zone_sequence" json,
  "estimated_time_minutes" int,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "picking_waves" (
  "wave_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "warehouse_id" int NOT NULL,
  "wave_number" varchar(50) UNIQUE,
  "status" wave_status,
  "priority" int DEFAULT 5,
  "total_items" int,
  "assigned_to" int,
  "start_time" datetime,
  "end_time" datetime,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "abc_classification" (
  "classification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int UNIQUE NOT NULL,
  "warehouse_id" int NOT NULL,
  "category" abc_category NOT NULL,
  "criteria" abc_criteria NOT NULL,
  "ranking" int,
  "last_updated" date
);

CREATE TABLE "reorder_rules" (
  "rule_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rule_name" varchar(100) NOT NULL,
  "product_id" int,
  "category_id" int,
  "supplier_id" int,
  "condition_type" condition_type,
  "condition_value" json,
  "action_type" action_type,
  "action_parameters" json,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "units_of_measure" (
  "uom_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(20) UNIQUE NOT NULL,
  "name" varchar(50) NOT NULL,
  "description" varchar(255)
);

CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(100) NOT NULL,
  "role" user_role DEFAULT 'staff',
  "warehouse_id" int,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "audit_log" (
  "audit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" varchar(100) NOT NULL,
  "record_id" int NOT NULL,
  "action" audit_action NOT NULL,
  "old_values" json,
  "new_values" json,
  "changed_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "changed_by" int
);

CREATE INDEX ON "products" ("sku");

CREATE INDEX ON "products" ("category_id");

CREATE INDEX ON "products" ("supplier_id");

CREATE UNIQUE INDEX ON "locations" ("warehouse_id", "location_code");

CREATE INDEX ON "inventory" ("product_id", "warehouse_id");

CREATE INDEX ON "purchase_orders" ("status", "order_date");

CREATE INDEX ON "stock_movements" ("product_id", "movement_date");

CREATE INDEX ON "stock_movements" ("reference_table", "reference_id");

CREATE UNIQUE INDEX ON "product_identifiers" ("identifier_type", "identifier_value");

CREATE UNIQUE INDEX ON "product_suppliers" ("product_id", "supplier_id");

COMMENT ON COLUMN "purchase_order_items"."total_price" IS 'Generated: quantity_ordered * unit_price';

COMMENT ON COLUMN "stock_adjustment_items"."quantity_after" IS 'Generated: quantity_before + quantity_adjusted';

COMMENT ON COLUMN "stock_adjustment_items"."adjustment_value" IS 'Generated: quantity_adjusted * cost_price';

COMMENT ON COLUMN "stocktake_items"."variance" IS 'Generated: counted_quantity - system_quantity';

COMMENT ON COLUMN "reconciliation_rules"."notify_users" IS 'Array of user IDs to notify';

COMMENT ON COLUMN "product_suppliers"."priority" IS '1 = primary, 2 = secondary, etc.';

COMMENT ON COLUMN "picking_routes"."zone_sequence" IS 'Array of zone IDs in optimal order';

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "products" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id");

ALTER TABLE "locations" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id");

ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "purchase_order_items" ADD FOREIGN KEY ("po_id") REFERENCES "purchase_orders" ("po_id");

ALTER TABLE "purchase_order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "stock_movements" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "stock_movements" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "stock_movements" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "stock_movements" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "stock_transfers" ADD FOREIGN KEY ("from_warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "stock_transfers" ADD FOREIGN KEY ("to_warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "stock_transfers" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "stock_transfer_items" ADD FOREIGN KEY ("transfer_id") REFERENCES "stock_transfers" ("transfer_id");

ALTER TABLE "stock_transfer_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "stock_transfer_items" ADD FOREIGN KEY ("from_location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "stock_transfer_items" ADD FOREIGN KEY ("to_location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("user_id");

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "stock_adjustment_items" ADD FOREIGN KEY ("adjustment_id") REFERENCES "stock_adjustments" ("adjustment_id");

ALTER TABLE "stock_adjustment_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "stock_takes" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "stock_takes" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "stocktake_items" ADD FOREIGN KEY ("stocktake_id") REFERENCES "stock_takes" ("stocktake_id");

ALTER TABLE "stocktake_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "stocktake_items" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "stocktake_items" ADD FOREIGN KEY ("counted_by") REFERENCES "users" ("user_id");

ALTER TABLE "reconciliation_rules" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "reconciliation_rules" ADD FOREIGN KEY ("product_category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "inventory_forecasting" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventory_forecasting" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "shrinkage_incidents" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "shrinkage_incidents" ADD FOREIGN KEY ("detected_by") REFERENCES "users" ("user_id");

ALTER TABLE "cycle_count_schedule" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "cycle_count_schedule" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("user_id");

ALTER TABLE "product_identifiers" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "product_identifiers" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "location_history" ADD FOREIGN KEY ("identifier_id") REFERENCES "product_identifiers" ("identifier_id");

ALTER TABLE "location_history" ADD FOREIGN KEY ("from_location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "location_history" ADD FOREIGN KEY ("to_location_id") REFERENCES "locations" ("location_id");

ALTER TABLE "location_history" ADD FOREIGN KEY ("scanned_by") REFERENCES "users" ("user_id");

ALTER TABLE "product_suppliers" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "product_suppliers" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id");

ALTER TABLE "picking_routes" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "picking_waves" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "picking_waves" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("user_id");

ALTER TABLE "abc_classification" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "abc_classification" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "reorder_rules" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "reorder_rules" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "reorder_rules" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id");

ALTER TABLE "users" ADD FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("warehouse_id");

ALTER TABLE "audit_log" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("user_id");
